import com.encima.Message

import com.encima.dwc.DarwinCore

import com.encima.dwc.Occurrence

import com.encima.dwc.Location

import com.encima.dwc.Species

import com.encima.dwc.Identification

rule "Hello World 2"
	when message:Message (type=="Test")
	then System.out.println("Test, Drools!"); 
	end
	
rule "Time Frame"
	when
		dwc:DarwinCore(occ.getLocationID()==1)
	then
		System.out.println("Occurence in site 1, animals here are: Clouded Leopard, Malay Civets and Small Mammals");
	end
